### ISSUE TITLE
Config deprecation warning

### ISSUE THREAD

**Issue by arananegra** [ThomZz/ts-jest-mock-import-meta#3]
Hi! Great job. This was the only solution I can find that it actually works!

However, the console outputs a warning about the way this project is defined in the jest.config.json file:

```
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
```

I have tried to change the config from what you have in your readme to the following:

```
"transform": {
    "\"^.+\\\\.(ts|tsx)$\"": [
      "ts-jest",
      {
        "diagnostics": {
          "ignoreCodes": [
            1343
          ]
        },
        "astTransformers": {
          "before": [
            {
              "path": "node_modules/ts-jest-mock-import-meta",
              "options": {
                "metaObjectReplacement": {
                  "url": "https://www.url.com"
                }
              }
            }
          ]
        }
      }
    ]
  }
```

However, doing this make the problem appear again.

Can you provide an updated way of doing this config or a hint of where is my problem?

Thanks!

**Comment by ThomZz** [comment]
Hey @arananegra, you are right, but that change on ts-jest side is really recent (since v29.0).
https://kulshekhar.github.io/ts-jest/docs/getting-started/options/
Based on their documentation, your config seems right.
The problem is appearing again because your typescript files are simply not processed by the transformer, because ts files are not matching the regex you provide.
Try with `^.+\\.tsx?$`, and tell me if it's better.

Don't hesitate to give the repo a star !

**Comment by arananegra** [comment]
Hi again. With this config the warns disappeared:

```
// more jest.config.json config...
  "transform": {
    "^.+\\.tsx?$": [
      "ts-jest",
      {
        "diagnostics": {
          "ignoreCodes": [
            1343
          ]
        },
        "astTransformers": {
          "before": [
            {
              "path": "node_modules/ts-jest-mock-import-meta",
              "options": {
                "metaObjectReplacement": {
                  "url": "https://www.url.com"
                }
              }
            }
          ]
        }
      }
    ]
  },
```

It would be nice if you update the documentation for this change. Of course, your repo deserves a start! Thank you again!
