### ISSUE TITLE
Not getting this plugin to work

### ISSUE THREAD

**Issue by master117** [ThomZz/ts-jest-mock-import-meta#8]
On JEST 29.2.1

jest.config.ts:

```
import type { JestConfigWithTsJest } from "ts-jest";

const jestConfig: JestConfigWithTsJest = {
    preset: "ts-jest",
    testEnvironment: "jsdom",
    testEnvironmentOptions: {
        testURL: "http://localhost:8888",
    },
    transform: {
        "^.+\\.tsx?$": [
            "ts-jest",
            {
                diagnostics: {
                    ignoreCodes: [1343],
                },
                astTransformers: {
                    before: [
                        {
                            path: "node_modules/ts-jest-mock-import-meta", // or, alternatively, 'ts-jest-mock-import-meta' directly, without node_modules.
                            options: {
                                metaObjectReplacement: {
                                    env: {
                                        PROD: false,
                                        DEV: true,
                                    },
                                    url: "https://www.url.com",
                                },
                            },
                        },
                    ],
                },
            },
        ],
        // process `*.tsx` files with `ts-jest`
    },
    moduleNameMapper: {
        "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
        "\\.(css|less|scss)$": "identity-obj-proxy",
    },
};

export default jestConfig;
```

![grafik](https://github.com/ThomZz/ts-jest-mock-import-meta/assets/444009/c063a662-19e6-45f6-ae83-789fb9051894)

Note that this is on untested files, which jest is rgabbing for coverage info via `jest --coverage --collectCoverageFrom='src/**/*.{ts,tsx}`
No tested file currently contains meta.

Please let me know if there is any other info you require.

**Comment by ThomZz** [comment]
Hi @master117 !
Is every concerned files are well included within the typescript conmpilation (files, or include property in the root `tsconfig.json`) ?.
ts-jest is using the root `tsconfig.json` by default if no `tsconfig` configuration property is provided.

**Comment by ThomZz** [comment]
After a quick investigation, it seems that "untested files" (and files that are not imported by any of your tests), are not processed by ts-jest, therefore, astTransformer are not applied.

So, if files that you specify within the --collectCoverageFrom options contains "import.meta" statements, they will not be transformed by ts-jest, but by a simplier typescript processor (?) provided by jest directly.

https://github.com/kulshekhar/ts-jest/issues/3207

**Comment by master117** [comment]
> After a quick investigation, it seems that "untested files" (and files that are not imported by any of your tests), are not processed by ts-jest, therefore, astTransformer are not applied.
> 
> So, if files that you specify within the --collectCoverageFrom options contains "import.meta" statements, they will not be transformed by ts-jest, but by a simplier typescript processor (?) provided by jest directly.
> 
> [kulshekhar/ts-jest#3207](https://github.com/kulshekhar/ts-jest/issues/3207)

Ah, good to know. Nothing you can do about that I guess. Thank you for the help!
